// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sample_MachineTest.DatabaseConnection.DatabaseClasses
{
    public partial class Employee
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public int DepartmentId { get; set; }
    }
}